name: Fly Deploy

on:
  # Only run this on main branch after Test workflow completed.
  workflow_run:
    workflows: [Test]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    # Only deploy if the Test workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
